### ISSUE TITLE
Implement pub/sub

### ISSUE THREAD

**Issue by SpaceK33z** [CodeYellowBV/cy-time#4]
The frontend can subscribe to something with:

```json5
{
	"type": "subscribe",
	"target": "entry",
	"requestId": "123e4567-e89b-12d3-a456-426655440000", // generated by frontend
	"data": {
		"user": 1 // optional scoping
	}
}
```

The backend will now send events to the frontend like this:

```json5
{
	"type": "publish",
	"target": "entry",
	"requestId": "123e4567-e89b-12d3-a456-426655440000",
	"data": {
		"add": [],
		"update": [{ "id": 1, ... }],
		"delete": []
	}
}
```

To unsubscribe:

```json5
{
	"type": "unsubscribe",
	"requestId": "123e4567-e89b-12d3-a456-426655440000" // generated by frontend
}
```

Immediately after subscribing, the backend will send an initial list of models by using the `publish` type above with all models in the `add` array.

**Comment by JasperStam** [comment]
What should the backend do on a publish when a socket has been subscribed with different requestIds with overlapping scope ?

**Comment by SpaceK33z** [comment]
Only publish it to to the socket with the request id I think.
