### ISSUE TITLE
Implement chat functionality

### ISSUE THREAD

**Issue by rutger** [CodeYellowBV/cy-time#6]
Also add Snapchat-like '24 hour stories' to share with friends on the platform.

**Comment by RogerKemp** [comment]
Don't forget about STICKERS!!!

**Comment by SpaceK33z** [comment]
OH fuck I need my stickers

![screen shot 2017-03-31 at 18 03 21](https://cloud.githubusercontent.com/assets/533616/24558698/5908c8a4-163c-11e7-938f-55673797021f.png)
